# Generated by Django 3.1.5 on 2021-01-05 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_preferences',
            field=models.ManyToManyField(blank=True, null=True, related_name='date_ideas', to='preferences.Preferences'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
