# Generated by Django 3.1.5 on 2021-01-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='dining_preference',
            field=models.ManyToManyField(blank=True, to='preferences.Dining'),
        ),
        migrations.AddField(
            model_name='user',
            name='entertainment_preference',
            field=models.ManyToManyField(blank=True, to='preferences.Entertainment'),
        ),
        migrations.AddField(
            model_name='user',
            name='out_doors_preference',
            field=models.ManyToManyField(blank=True, to='preferences.OutDoors'),
        ),
        migrations.AddField(
            model_name='user',
            name='stay_home_preference',
            field=models.ManyToManyField(blank=True, to='preferences.StayHome'),
        ),
    ]
