# Generated by Django 3.1.5 on 2021-01-05 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20210105_2020'),
        ('users', '0002_auto_20210105_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_preferences',
            field=models.ManyToManyField(blank=True, related_name='date_ideas', to='preferences.Preferences'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends_list',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
