# Generated by Django 3.1.5 on 2021-01-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
