# Generated by Django 3.1.5 on 2021-01-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210113_2237'),
        ('users', '0002_auto_20210114_0104'),
    ]

    operations = [
    ]
