# Generated by Django 3.1.5 on 2021-01-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210114_0104'),
        ('users', '0003_auto_20210113_2237'),
    ]

    operations = [
    ]
