# Generated by Django 3.1.5 on 2021-01-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20210114_2127'),
        ('users', '0004_merge_20210114_2100'),
    ]

    operations = [
    ]
