# Generated by Django 3.1.5 on 2021-01-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20210115_2343'),
        ('users', '0005_merge_20210116_2004'),
    ]

    operations = [
    ]
