# Generated by Django 3.1.5 on 2021-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20210105_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='entertainment_choices',
        ),
        migrations.AddField(
            model_name='preferences',
            name='entertainment',
            field=models.ManyToManyField(to='preferences.Entertainment'),
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='outdoors',
        ),
        migrations.AddField(
            model_name='preferences',
            name='outdoors',
            field=models.ManyToManyField(to='preferences.OutDoors'),
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='stay_home',
        ),
        migrations.AddField(
            model_name='preferences',
            name='stay_home',
            field=models.ManyToManyField(to='preferences.StayHome'),
        ),
    ]
