# Generated by Django 3.1.5 on 2021-01-11 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesNightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('when_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('dining_category', models.ManyToManyField(blank=True, null=True, to='preferences.Dining')),
                ('entertainment_category', models.ManyToManyField(blank=True, null=True, to='preferences.Entertainment')),
                ('out_doors_category', models.ManyToManyField(blank=True, null=True, to='preferences.OutDoors')),
                ('stay_home_category', models.ManyToManyField(blank=True, null=True, to='preferences.StayHome')),
                ('users_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one', to=settings.AUTH_USER_MODEL)),
                ('users_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
