# Generated by Django 3.1.5 on 2021-01-13 00:21

import dates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesnightmodel',
            name='confirmed_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=dates.models.ActivityModel, to='dates.activitymodel'),
        ),
    ]
