# Generated by Django 3.1.5 on 2021-01-07 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datesnightmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='datesnightmodel',
            name='dining_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.dining'),
        ),
        migrations.AddField(
            model_name='datesnightmodel',
            name='entertainment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.entertainment'),
        ),
        migrations.AddField(
            model_name='datesnightmodel',
            name='out_doors_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.outdoors'),
        ),
        migrations.AddField(
            model_name='datesnightmodel',
            name='stay_home_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.stayhome'),
        ),
    ]
