# Generated by Django 3.1.5 on 2021-01-14 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('dates', '0002_auto_20210113_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesnightmodel',
            name='confirmed_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dates.activitymodel'),
        ),
        migrations.AlterField(
            model_name='datesnightmodel',
            name='dining_category',
            field=models.ManyToManyField(blank=True, to='preferences.Dining'),
        ),
        migrations.AlterField(
            model_name='datesnightmodel',
            name='entertainment_category',
            field=models.ManyToManyField(blank=True, to='preferences.Entertainment'),
        ),
        migrations.AlterField(
            model_name='datesnightmodel',
            name='out_doors_category',
            field=models.ManyToManyField(blank=True, to='preferences.OutDoors'),
        ),
        migrations.AlterField(
            model_name='datesnightmodel',
            name='stay_home_category',
            field=models.ManyToManyField(blank=True, to='preferences.StayHome'),
        ),
    ]
