# Generated by Django 3.1.5 on 2021-01-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('dates', '0002_auto_20210107_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datesnightmodel',
            name='dining_category',
        ),
        migrations.AddField(
            model_name='datesnightmodel',
            name='dining_category',
            field=models.ManyToManyField(blank=True, null=True, to='preferences.Dining'),
        ),
    ]
