# Generated by Django 3.1.5 on 2021-01-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_night',
        ),
    ]
