# Generated by Django 3.1.5 on 2021-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
