# Generated by Django 3.1.5 on 2021-01-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
        ('notifications', '0002_remove_notification_date_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_night',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dates.datesnightmodel'),
        ),
    ]
