# Generated by Django 3.1.5 on 2021-01-07 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_notification_date_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='received_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='received_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
